import { MCPClient } from '@mastra/mcp'

const DEMO_CONNECTION_STRING = process.env.MONGODB_DEMO_CONNECTION_STRING

// Destructive / housekeeping tools the workshop doesn't need. Disabling them
// outright (rather than relying on the MCP server's confirmation/elicitation
// flow, which an automated non-interactive agent may not be able to answer)
// keeps behavior predictable for a live demo and removes any chance of the
// agent wiping shared workshop data.
const DISABLED_TOOLS = [
  'drop-database',
  'drop-collection',
  'delete-many',
  'update-many',
  'rename-collection',
  'drop-index',
  'mongodb-logs',
  'export',
  'disconnect',
  'list-connections',
].join(',')

let cachedClient: MCPClient | null = null

/**
 * Lazily spawns (and caches) the local MongoDB MCP Server as a stdio
 * subprocess, scoped to the `workshop_demo_user` credential (readWrite on
 * `streaming_catalog` only — no visibility into the admin settings db).
 *
 * No Voyage API key is configured here: the shared vector search index uses
 * MongoDB Atlas's Automated Embedding (`autoEmbed` field type, voyage-4
 * model), which Atlas hosts and manages entirely server-side. Embeddings are
 * generated by Atlas itself at insert- and query-time — no embedding key or
 * client-side embedding step is needed in this app at all.
 */
export async function getMongoDbTools() {
  if (!DEMO_CONNECTION_STRING) {
    throw new Error(
      'MONGODB_DEMO_CONNECTION_STRING is missing from your .env file. Ask the workshop admin for the shared credentials.',
    )
  }

  if (!cachedClient) {
    cachedClient = new MCPClient({
      id: 'mongodb-demo-client',
      servers: {
        mongodb: {
          command: 'npx',
          args: ['-y', 'mongodb-mcp-server@latest', '--disabledTools', DISABLED_TOOLS],
          env: {
            MDB_MCP_CONNECTION_STRING: DEMO_CONNECTION_STRING,
          },
        },
      },
    })
  }

  return cachedClient.listTools()
}
